import { render, screen, act } from '@testing-library/react';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { describe, it, afterEach, expect } from 'vitest';
import { SectionPage } from '@/pages/SectionPage';
import { useStore } from '@/store';

describe('SectionPage', () => {
  afterEach(() => {
    act(() => {
      useStore.setState({ docs: [], config: null });
    });
  });

  it('falls back to all entries when no match exists', () => {
    act(() => {
      useStore.setState({
        docs: [
          {
            id: 'alpha',
            name: 'alpha',
            kind: 'function',
            fileName: 'src/store/index.ts',
            module: 'src/store/index',
            position: { line: 1, column: 0 },
            signature: 'function alpha(): void',
          },
        ],
        config: {
          sidebar: [{ title: 'API Reference', autogenerate: 'src/api/' }],
        },
      });
    });

    render(
      <MemoryRouter initialEntries={['/section/api-reference']}>
        <Routes>
          <Route path="/section/:slug" element={<SectionPage />} />
        </Routes>
      </MemoryRouter>
    );

    expect(screen.getByText('API Reference')).toBeInTheDocument();
    expect(screen.getByText(/No entries matched/i)).toBeInTheDocument();
    expect(screen.getByText('alpha')).toBeInTheDocument();
  });

  it('uses matching section prefix and builds id-based entry links', () => {
    act(() => {
      useStore.setState({
        docs: [
          {
            id: 'abcd1234',
            name: 'doWork',
            kind: 'function',
            fileName: 'src/api/work.ts',
            module: 'src/api/work',
            position: { line: 1, column: 0 },
            signature: 'function doWork(): void',
          },
        ],
        config: {
          sidebar: [{ title: 'API Reference', autogenerate: 'src/api/' }],
        },
      });
    });

    render(
      <MemoryRouter initialEntries={['/section/api-reference']}>
        <Routes>
          <Route path="/section/:slug" element={<SectionPage />} />
        </Routes>
      </MemoryRouter>
    );

    expect(screen.getByText(/Autogenerated from "src\/api\/"/i)).toBeInTheDocument();
    const entryLink = screen.getByRole('link', { name: 'doWork' });
    expect(entryLink).toHaveAttribute('href', '/function/abcd1234/dowork');
  });

  it('renders not found state when sidebar section is missing or not autogenerate', () => {
    act(() => {
      useStore.setState({
        docs: [],
        config: {
          sidebar: [{ title: 'Manual Section', path: '/docs/manual.md' }],
        },
      });
    });

    render(
      <MemoryRouter initialEntries={['/section/manual-section']}>
        <Routes>
          <Route path="/section/:slug" element={<SectionPage />} />
        </Routes>
      </MemoryRouter>
    );

    expect(screen.getByText('Section not found')).toBeInTheDocument();
    expect(screen.getByText(/missing or not configured/i)).toBeInTheDocument();
  });

  it('normalizes backslashes, shows class pluralization, and truncates long lists', () => {
    act(() => {
      useStore.setState({
        docs: [
          {
            id: 'c1',
            name: 'AlphaClass',
            kind: 'class',
            fileName: 'src\\api\\classes\\alpha.ts',
            module: 'src\\api\\classes\\alpha',
            position: { line: 1, column: 0 },
            signature: 'class AlphaClass {}',
          },
          {
            id: 'c2',
            name: 'BetaClass',
            kind: 'class',
            fileName: 'src\\api\\classes\\beta.ts',
            module: 'src\\api\\classes\\beta',
            position: { line: 1, column: 0 },
            signature: 'class BetaClass {}',
          },
          {
            id: 'f1',
            name: 'fn1',
            kind: 'function',
            fileName: 'src\\api\\fn1.ts',
            module: 'src\\api\\fn1',
            position: { line: 1, column: 0 },
            signature: 'function fn1(): void',
          },
          {
            id: 'f2',
            name: 'fn2',
            kind: 'function',
            fileName: 'src\\api\\fn2.ts',
            module: 'src\\api\\fn2',
            position: { line: 1, column: 0 },
            signature: 'function fn2(): void',
          },
          {
            id: 'f3',
            name: 'fn3',
            kind: 'function',
            fileName: 'src\\api\\fn3.ts',
            module: 'src\\api\\fn3',
            position: { line: 1, column: 0 },
            signature: 'function fn3(): void',
          },
          {
            id: 'f4',
            name: 'fn4',
            kind: 'function',
            fileName: 'src\\api\\fn4.ts',
            module: 'src\\api\\fn4',
            position: { line: 1, column: 0 },
            signature: 'function fn4(): void',
          },
          {
            id: 'f5',
            name: 'fn5',
            kind: 'function',
            fileName: 'src\\api\\fn5.ts',
            module: 'src\\api\\fn5',
            position: { line: 1, column: 0 },
            signature: 'function fn5(): void',
          },
          {
            id: 'f6',
            name: 'fn6',
            kind: 'function',
            fileName: 'src\\api\\fn6.ts',
            module: 'src\\api\\fn6',
            position: { line: 1, column: 0 },
            signature: 'function fn6(): void',
          },
          {
            id: 'f7',
            name: 'fn7',
            kind: 'function',
            fileName: 'src\\api\\fn7.ts',
            module: 'src\\api\\fn7',
            position: { line: 1, column: 0 },
            signature: 'function fn7(): void',
          },
        ],
        config: {
          sidebar: [{ title: 'API Reference', autogenerate: 'src/api/' }],
        },
      });
    });

    render(
      <MemoryRouter initialEntries={['/section/api-reference']}>
        <Routes>
          <Route path="/section/:slug" element={<SectionPage />} />
        </Routes>
      </MemoryRouter>
    );

    expect(screen.getByText(/Autogenerated from "src\/api\/"/i)).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: 'classes' })).toBeInTheDocument();
    expect(screen.getByText('+1 more')).toBeInTheDocument();
    expect(screen.getByRole('link', { name: 'AlphaClass' })).toHaveAttribute(
      'href',
      '/class/c1/alphaclass'
    );
  });
});
