import { useMemo } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Badge } from '@/components/ui/badge';
import { Card } from '@/components/ui/card';
import { useStore, DocEntry } from '@/store';
import { slugify } from '@/lib/utils';

function pluralize(kind: string, count: number): string {
  const singular = kind.toLowerCase();
  if (count === 1) return singular;
  if (singular === 'class') return 'classes';
  if (
    singular.endsWith('s') ||
    singular.endsWith('x') ||
    singular.endsWith('ch') ||
    singular.endsWith('sh')
  ) {
    return `${singular}es`;
  }
  return `${singular}s`;
}

export function SectionPage() {
  const { slug } = useParams();
  const docs = useStore((state) => state.docs);
  const config = useStore((state) => state.config);

  const section = useMemo(
    () =>
      config?.sidebar?.find((item) => item.autogenerate && slugify(item.title) === slug) ?? null,
    [config?.sidebar, slug]
  );

  if (!section || !section.autogenerate) {
    return (
      <Card className="border-border/60 bg-card/70 p-8">
        <h1 className="text-2xl font-semibold">Section not found</h1>
        <p className="mt-2 text-sm text-muted-foreground">
          The section you requested is missing or not configured.
        </p>
      </Card>
    );
  }

  const prefix = section.autogenerate.replace(/\\/g, '/');
  const filtered = docs.filter((doc) => {
    const moduleName = doc.module?.replace(/\\/g, '/') ?? '';
    const fileName = doc.fileName.replace(/\\/g, '/');
    return moduleName.startsWith(prefix) || fileName.startsWith(prefix);
  });

  const entries = filtered.length > 0 ? filtered : docs;
  const isFallback = filtered.length === 0;

  const grouped = entries.reduce<Record<string, DocEntry[]>>((acc, doc) => {
    const kindDocs = acc[doc.kind] ?? [];
    kindDocs.push(doc);
    acc[doc.kind] = kindDocs;
    return acc;
  }, {});

  const kindEntries = Object.entries(grouped).sort(([a], [b]) => a.localeCompare(b));
  const moduleCount = new Set(entries.map((doc) => doc.module || doc.fileName)).size;

  return (
    <div className="space-y-10">
      <section className="rounded-2xl border border-border/60 bg-card/70 p-8 shadow-glow surface-glass">
        <div className="space-y-4">
          <Badge
            variant="outline"
            className="rounded-full px-3 py-1 text-[11px] uppercase tracking-[0.3em]"
          >
            Section
          </Badge>
          <div>
            <h1 className="text-3xl font-semibold tracking-tight">{section.title}</h1>
            <p className="mt-2 text-sm text-muted-foreground">
              {isFallback
                ? `No entries matched "${section.autogenerate}". Showing all documented entries instead.`
                : `Autogenerated from "${section.autogenerate}".`}
            </p>
          </div>
          <div className="grid gap-4 sm:grid-cols-3">
            <div className="rounded-xl border border-border/60 bg-background/70 p-4">
              <p className="text-[11px] font-semibold uppercase tracking-[0.3em] text-muted-foreground">
                Entries
              </p>
              <p className="mt-2 text-2xl font-semibold">{entries.length}</p>
            </div>
            <div className="rounded-xl border border-border/60 bg-background/70 p-4">
              <p className="text-[11px] font-semibold uppercase tracking-[0.3em] text-muted-foreground">
                Kinds
              </p>
              <p className="mt-2 text-2xl font-semibold">{Object.keys(grouped).length}</p>
            </div>
            <div className="rounded-xl border border-border/60 bg-background/70 p-4">
              <p className="text-[11px] font-semibold uppercase tracking-[0.3em] text-muted-foreground">
                Modules
              </p>
              <p className="mt-2 text-2xl font-semibold">{moduleCount}</p>
            </div>
          </div>
        </div>
      </section>

      <section className="space-y-6">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div>
            <h2 className="text-2xl font-semibold tracking-tight">Browse by kind</h2>
            <p className="mt-1 text-sm text-muted-foreground">
              Jump into the surface area that matters most.
            </p>
          </div>
          <Badge variant="secondary" className="rounded-full px-3 py-1 text-xs">
            {entries.length} entries
          </Badge>
        </div>

        <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">
          {kindEntries.map(([kind, items]) => (
            <Card
              key={kind}
              className="relative overflow-hidden border-border/60 bg-card/70 p-6 shadow-md"
            >
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <h3 className="text-xl font-semibold capitalize">
                    {pluralize(kind, items.length)}
                  </h3>
                  <Badge variant="secondary" className="rounded-full">
                    {items.length}
                  </Badge>
                </div>
                <p className="text-sm text-muted-foreground">
                  {items.length} {pluralize(kind, items.length)} documented.
                </p>
                <ul className="space-y-2 text-sm">
                  {items.slice(0, 6).map((item) => (
                    <li key={item.id}>
                      <Link
                        to={`/${kind}/${item.name}`}
                        className="font-medium text-primary underline-offset-4 hover:underline"
                      >
                        {item.name}
                      </Link>
                    </li>
                  ))}
                  {items.length > 6 && (
                    <li className="text-xs text-muted-foreground">+{items.length - 6} more</li>
                  )}
                </ul>
              </div>
            </Card>
          ))}
        </div>
      </section>
    </div>
  );
}
